package com.curso.usojdbcmysql.practicas;

import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/* Generated by Together */
/**
 * Realizar una inserción en la base de datos, una actualización y un borrado. Muestra por consola la operación que se está
 * realizando y el número de filas afectada por la misma.
 * @author JMD
 * @version 1.0
 */
public class Practica_003 extends PracticaBase {

    public static void main(String[] args) {
        try {
            Practica_003 p = new Practica_003();
            p.ejecutar();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Practica_003.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void insercion() throws SQLException {
        Statement st = null;
        st = con.createStatement();
        final String ordenSQL = "INSERT INTO CONTACTOS (NOMBRE,APELLIDOS) VALUES('ABC','XYZ')";
        System.out.println("Realizando inserci�n...");
        int filas = st.executeUpdate(ordenSQL);
        System.out.println("Filas afectadas: " + filas);
        if (st != null) {
            st.close();
        }

    }

    private void actualizacion() throws SQLException {
        Statement st = null;
        st = con.createStatement();
        final String ordenSQL = "UPDATE CONTACTOS SET APELLIDOS = '123' WHERE NOMBRE = 'ABC'";
        System.out.println("Realizando actualizaci�n...");
        int filas = st.executeUpdate(ordenSQL);
        System.out.println("Filas afectadas: " + filas);
        if (st != null) {
            st.close();
        }
    }

    private void borrado() throws SQLException {
        Statement st = null;
        st = con.createStatement();
        final String ordenSQL = "DELETE FROM CONTACTOS WHERE APELLIDOS = '123'";
        System.out.println("Realizando borrado...");
        int filas = st.executeUpdate(ordenSQL);
        System.out.println("Filas afectadas: " + filas);
        if (st != null) {
            st.close();
        }
    }

    protected void accionEspecifica() throws SQLException {
        insercion();
        actualizacion();
        borrado();
    }
}
