/* Generated by Together */
package com.curso.usojdbcmysql.practicas;

import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Muestra un manejo sencillo de los metadatos a través de las interfaces ResultSetMetaData y DatabaseMetaData.
 * @author JMD
 * @version 1.0
 */
public class Practica_009 extends PracticaBase {

    public static void main(String[] args) {
        try {
            Practica_009 p = new Practica_009();
            p.ejecutar();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Practica_009.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void mostrarResultados(final ResultSet rs) throws SQLException {
        DatabaseMetaData dbmd = con.getMetaData();
        if (dbmd.supportsBatchUpdates()) {
            System.out.println("La base de datos soporta actualizaciones batch");
        } else {
            System.out.println("La base de no datos soporta actualizaciones batch");
        }
        ResultSetMetaData rsmd = rs.getMetaData();
        System.out.println("El ResultSet tiene " + rsmd.getColumnCount() + " columnas");
        for (int i = 1; i <= rsmd.getColumnCount(); i++) {
            String nombreDeColumna = rsmd.getColumnName(i);
            String tipoDeColumna = rsmd.getColumnTypeName(i);
            System.out.println("Columna " + i + ": " + nombreDeColumna + " " + tipoDeColumna);
        }
    }

    @Override
    protected void seleccion() throws SQLException {
        Statement st = null;
        ResultSet rs = null;
        st = con.createStatement();
        final String ordenSQL = "SELECT * FROM CONTACTOS";
        System.out.println("Realizando consulta...");
        rs = st.executeQuery(ordenSQL);
        mostrarResultados(rs);
        if (rs != null) {
            rs.close();
        }
        if (st != null) {
            st.close();
        }
    }

    protected void accionEspecifica() throws SQLException {
        seleccion();
    }
}
